package com.nickdegs.movelog.ui

import java.util.Locale

// iOS Strings.swift birebir: 12 dil. L(tr, en) çağrı yerleri DEĞİŞMEZ —
// cihaz dili tr ise Türkçe, en ise İngilizce, değilse TRANS[en][lang] (yoksa İngilizce'ye düşer).
private val SUPPORTED = listOf("en", "tr", "de", "fr", "es", "it", "pt", "ru", "ja", "zh", "ko", "ar")

private fun currentLang(): String {
    val code = Locale.getDefault().language
    return if (SUPPORTED.contains(code)) code else "en"
}

// İngilizce anahtara göre 12-dil çeviri (eksikse İngilizce'ye düşer)
private val TRANS: Map<String, Map<String, String>> = mapOf(
    "Routes · Activity · Live location" to mapOf("tr" to "Rotalar · Aktivite · Canlı konum","de" to "Routen · Aktivität · Live-Standort","fr" to "Itinéraires · Activité · Position en direct","es" to "Rutas · Actividad · Ubicación en vivo","it" to "Percorsi · Attività · Posizione live","pt" to "Rotas · Atividade · Localização ao vivo","ru" to "Маршруты · Активность · Геопозиция","ja" to "ルート · アクティビティ · 現在地","zh" to "路线 · 活动 · 实时位置","ko" to "경로 · 활동 · 실시간 위치","ar" to "المسارات · النشاط · الموقع المباشر"),
    "Username" to mapOf("tr" to "Kullanıcı","de" to "Benutzer","fr" to "Identifiant","es" to "Usuario","it" to "Utente","pt" to "Usuário","ru" to "Пользователь","ja" to "ユーザー名","zh" to "用户名","ko" to "사용자 이름","ar" to "اسم المستخدم"),
    "Password" to mapOf("tr" to "Parola","de" to "Passwort","fr" to "Mot de passe","es" to "Contraseña","it" to "Password","pt" to "Senha","ru" to "Пароль","ja" to "パスワード","zh" to "密码","ko" to "비밀번호","ar" to "كلمة المرور"),
    "Sign in" to mapOf("tr" to "Giriş yap","de" to "Anmelden","fr" to "Se connecter","es" to "Iniciar sesión","it" to "Accedi","pt" to "Entrar","ru" to "Войти","ja" to "サインイン","zh" to "登录","ko" to "로그인","ar" to "تسجيل الدخول"),
    "Routes" to mapOf("tr" to "Rotalar","de" to "Routen","fr" to "Itinéraires","es" to "Rutas","it" to "Percorsi","pt" to "Rotas","ru" to "Маршруты","ja" to "ルート","zh" to "路线","ko" to "경로","ar" to "المسارات"),
    "Chat" to mapOf("tr" to "Sohbet","de" to "Chat","fr" to "Discussion","es" to "Chat","it" to "Chat","pt" to "Conversa","ru" to "Чат","ja" to "チャット","zh" to "聊天","ko" to "채팅","ar" to "الدردشة"),
    "Map" to mapOf("tr" to "Harita","de" to "Karte","fr" to "Carte","es" to "Mapa","it" to "Mappa","pt" to "Mapa","ru" to "Карта","ja" to "マップ","zh" to "地图","ko" to "지도","ar" to "الخريطة"),
    "Stats" to mapOf("tr" to "İstatistik","de" to "Statistik","fr" to "Stats","es" to "Stats","it" to "Statistiche","pt" to "Estatísticas","ru" to "Статистика","ja" to "統計","zh" to "统计","ko" to "통계","ar" to "الإحصاءات"),
    "Profile" to mapOf("tr" to "Profil","de" to "Profil","fr" to "Profil","es" to "Perfil","it" to "Profilo","pt" to "Perfil","ru" to "Профиль","ja" to "プロフィール","zh" to "个人资料","ko" to "프로필","ar" to "الملف"),
    "Live GPS" to mapOf("tr" to "Canlı GPS","de" to "Live-GPS","fr" to "GPS en direct","es" to "GPS en vivo","it" to "GPS live","pt" to "GPS ao vivo","ru" to "GPS вживую","ja" to "ライブGPS","zh" to "实时 GPS","ko" to "실시간 GPS","ar" to "GPS مباشر"),
    "Play" to mapOf("tr" to "İzle","de" to "Ansehen","fr" to "Lire","es" to "Ver","it" to "Guarda","pt" to "Assistir","ru" to "Смотреть","ja" to "再生","zh" to "播放","ko" to "재생","ar" to "تشغيل"),
    "Motorcycle" to mapOf("tr" to "Motosiklet","de" to "Motorrad","fr" to "Moto","es" to "Motocicleta","it" to "Moto","pt" to "Motocicleta","ru" to "Мотоцикл","ja" to "バイク","zh" to "摩托车","ko" to "오토바이","ar" to "دراجة نارية"),
    "Cycling" to mapOf("tr" to "Bisiklet","de" to "Radfahren","fr" to "Vélo","es" to "Ciclismo","it" to "Ciclismo","pt" to "Ciclismo","ru" to "Велосипед","ja" to "サイクリング","zh" to "骑行","ko" to "자전거","ar" to "دراجة"),
    "Running" to mapOf("tr" to "Koşu","de" to "Laufen","fr" to "Course","es" to "Correr","it" to "Corsa","pt" to "Corrida","ru" to "Бег","ja" to "ランニング","zh" to "跑步","ko" to "달리기","ar" to "الجري"),
    "Walking" to mapOf("tr" to "Yürüyüş","de" to "Gehen","fr" to "Marche","es" to "Caminar","it" to "Camminata","pt" to "Caminhada","ru" to "Ходьба","ja" to "ウォーキング","zh" to "步行","ko" to "걷기","ar" to "المشي"),
    "Other" to mapOf("tr" to "Diğer","de" to "Sonstige","fr" to "Autre","es" to "Otro","it" to "Altro","pt" to "Outro","ru" to "Другое","ja" to "その他","zh" to "其他","ko" to "기타","ar" to "أخرى"),
    "Total routes" to mapOf("tr" to "Toplam rota","de" to "Routen gesamt","fr" to "Itinéraires au total","es" to "Rutas totales","it" to "Percorsi totali","pt" to "Total de rotas","ru" to "Всего маршрутов","ja" to "ルート合計","zh" to "路线总数","ko" to "총 경로","ar" to "إجمالي المسارات"),
    "Latest route" to mapOf("tr" to "Son rota","de" to "Letzte Route","fr" to "Dernier itinéraire","es" to "Última ruta","it" to "Ultimo percorso","pt" to "Última rota","ru" to "Последний маршрут","ja" to "最新のルート","zh" to "最新路线","ko" to "최근 경로","ar" to "أحدث مسار"),
    "Move Log member" to mapOf("tr" to "Move Log üyesi","de" to "Move Log-Mitglied","fr" to "Membre Move Log","es" to "Miembro de Move Log","it" to "Membro Move Log","pt" to "Membro Move Log","ru" to "Участник Move Log","ja" to "Move Log メンバー","zh" to "Move Log 会员","ko" to "Move Log 회원","ar" to "عضو في Move Log"),
    "Friends" to mapOf("tr" to "Arkadaşlar","de" to "Freunde","fr" to "Amis","es" to "Amigos","it" to "Amici","pt" to "Amigos","ru" to "Друзья","ja" to "友だち","zh" to "好友","ko" to "친구","ar" to "الأصدقاء"),
    "Add friend" to mapOf("tr" to "Arkadaş ekle","de" to "Freund hinzufügen","fr" to "Ajouter un ami","es" to "Añadir amigo","it" to "Aggiungi amico","pt" to "Adicionar amigo","ru" to "Добавить друга","ja" to "友だちを追加","zh" to "添加好友","ko" to "친구 추가","ar" to "إضافة صديق"),
    "Typography" to mapOf("tr" to "Tipografi","de" to "Typografie","fr" to "Typographie","es" to "Tipografía","it" to "Tipografia","pt" to "Tipografia","ru" to "Типографика","ja" to "書体","zh" to "字体","ko" to "서체","ar" to "الخطوط"),
    "Default" to mapOf("tr" to "Varsayılan","de" to "Standard","fr" to "Par défaut","es" to "Predeterminado","it" to "Predefinito","pt" to "Padrão","ru" to "По умолчанию","ja" to "デフォルト","zh" to "默认","ko" to "기본","ar" to "افتراضي"),
    "Appearance" to mapOf("tr" to "Görünüm","de" to "Darstellung","fr" to "Apparence","es" to "Apariencia","it" to "Aspetto","pt" to "Aparência","ru" to "Оформление","ja" to "外観","zh" to "外观","ko" to "화면 모드","ar" to "المظهر"),
    "Light" to mapOf("tr" to "Açık","de" to "Hell","fr" to "Clair","es" to "Claro","it" to "Chiaro","pt" to "Claro","ru" to "Светлая","ja" to "ライト","zh" to "浅色","ko" to "라이트","ar" to "فاتح"),
    "Dark" to mapOf("tr" to "Koyu","de" to "Dunkel","fr" to "Sombre","es" to "Oscuro","it" to "Scuro","pt" to "Escuro","ru" to "Тёмная","ja" to "ダーク","zh" to "深色","ko" to "다크","ar" to "داكن"),
    "Sign out" to mapOf("tr" to "Çıkış","de" to "Abmelden","fr" to "Déconnexion","es" to "Cerrar sesión","it" to "Esci","pt" to "Sair","ru" to "Выйти","ja" to "サインアウト","zh" to "退出","ko" to "로그아웃","ar" to "تسجيل الخروج"),
    "Message" to mapOf("tr" to "Mesaj","de" to "Nachricht","fr" to "Message","es" to "Mensaje","it" to "Messaggio","pt" to "Mensagem","ru" to "Сообщение","ja" to "メッセージ","zh" to "消息","ko" to "메시지","ar" to "رسالة"),
    "Online" to mapOf("tr" to "Çevrimiçi","de" to "Online","fr" to "En ligne","es" to "En línea","it" to "Online","pt" to "Online","ru" to "В сети","ja" to "オンライン","zh" to "在线","ko" to "온라인","ar" to "متصل"),
    "Offline" to mapOf("tr" to "Çevrimdışı","de" to "Offline","fr" to "Hors ligne","es" to "Sin conexión","it" to "Offline","pt" to "Offline","ru" to "Не в сети","ja" to "オフライン","zh" to "离线","ko" to "오프라인","ar" to "غير متصل"),
    "Friend" to mapOf("tr" to "Arkadaş","de" to "Freund","fr" to "Ami","es" to "Amigo","it" to "Amico","pt" to "Amigo","ru" to "Друг","ja" to "友だち","zh" to "好友","ko" to "친구","ar" to "صديق"),
    "Route" to mapOf("tr" to "Rota","de" to "Route","fr" to "Itinéraire","es" to "Ruta","it" to "Percorso","pt" to "Rota","ru" to "Маршрут","ja" to "ルート","zh" to "路线","ko" to "경로","ar" to "مسار"),
    "My Videos" to mapOf("tr" to "Videolarım","de" to "Meine Videos","fr" to "Mes vidéos","es" to "Mis vídeos","it" to "I miei video","pt" to "Meus vídeos","ru" to "Мои видео","ja" to "マイビデオ","zh" to "我的视频","ko" to "내 동영상","ar" to "مقاطعي"),
    "No videos yet" to mapOf("tr" to "Henüz video yok","de" to "Noch keine Videos","fr" to "Aucune vidéo","es" to "Aún no hay vídeos","it" to "Ancora nessun video","pt" to "Ainda sem vídeos","ru" to "Видео пока нет","ja" to "動画はまだありません","zh" to "还没有视频","ko" to "아직 동영상이 없습니다","ar" to "لا توجد مقاطع بعد"),
    "Rendering…" to mapOf("tr" to "Hazırlanıyor…","de" to "Wird erstellt…","fr" to "Création…","es" to "Generando…","it" to "Generazione…","pt" to "Gerando…","ru" to "Создание…","ja" to "作成中…","zh" to "生成中…","ko" to "생성 중…","ar" to "جارٍ الإنشاء…"),
    "Rendering, playable when done" to mapOf("tr" to "Video hazırlanıyor, bitince izlenebilir","de" to "Wird erstellt – nach Fertigstellung abspielbar","fr" to "Création en cours – lisible une fois terminé","es" to "Generando, se podrá ver al terminar","it" to "Generazione, riproducibile al termine","pt" to "Gerando, reproduzível quando concluir","ru" to "Создаётся, можно посмотреть после готовности","ja" to "作成中。完了後に再生できます","zh" to "生成中，完成后即可播放","ko" to "생성 중, 완료되면 재생 가능","ar" to "جارٍ الإنشاء، يمكن تشغيله عند الانتهاء"),
    "Created: " to mapOf("tr" to "Üretildi: ","de" to "Erstellt: ","fr" to "Créé : ","es" to "Creado: ","it" to "Creato: ","pt" to "Criado: ","ru" to "Создано: ","ja" to "作成: ","zh" to "生成于：","ko" to "생성: ","ar" to "أُنشئ: "),
    "Auto" to mapOf("tr" to "Otonom","de" to "Automatisch","fr" to "Auto","es" to "Auto","it" to "Auto","pt" to "Auto","ru" to "Авто","ja" to "オート","zh" to "自动","ko" to "자동","ar" to "تلقائي"),
    "Auto 🔒" to mapOf("tr" to "Otonom 🔒","de" to "Automatisch 🔒","fr" to "Auto 🔒","es" to "Auto 🔒","it" to "Auto 🔒","pt" to "Auto 🔒","ru" to "Авто 🔒","ja" to "オート 🔒","zh" to "自动 🔒","ko" to "자동 🔒","ar" to "تلقائي 🔒"),
    "Short ≈15s, Medium ≈30s, Long scales with distance (max 60s)." to mapOf("tr" to "Kısa ≈15sn, Orta ≈30sn, Uzun rotaya göre (max 60sn). Süre rota uzunluğuna göre ölçeklenir.","de" to "Kurz ≈15 Sek., Mittel ≈30 Sek., Lang skaliert mit der Distanz (max. 60 Sek.).","fr" to "Court ≈15 s, Moyen ≈30 s, Long selon la distance (max 60 s).","es" to "Corto ≈15 s, Medio ≈30 s, Largo según la distancia (máx. 60 s).","it" to "Breve ≈15 s, Medio ≈30 s, Lungo in base alla distanza (max 60 s).","pt" to "Curto ≈15 s, Médio ≈30 s, Longo conforme a distância (máx. 60 s).","ru" to "Короткое ≈15 с, Среднее ≈30 с, Длинное зависит от дистанции (макс. 60 с).","ja" to "短い ≈15秒、中 ≈30秒、長いは距離に応じて（最大60秒）。","zh" to "短 ≈15秒，中 ≈30秒，长随距离变化（最长60秒）。","ko" to "짧게 ≈15초, 보통 ≈30초, 길게 거리에 따라(최대 60초).","ar" to "قصير ≈15 ث، متوسط ≈30 ث، طويل حسب المسافة (بحد أقصى 60 ث)."),
    "Auto: length fully scales with your route (max 3 min). Great for city trips. Premium, once a day." to mapOf("tr" to "Otonom: süre TAMAMEN rotaya göre ayarlanır (max 3 dk). Şehir yolculukları için ideal. Premium, günde 1.","de" to "Automatisch: Länge richtet sich ganz nach deiner Route (max. 3 Min.). Ideal für Stadtfahrten. Premium, einmal täglich.","fr" to "Auto : la durée s'adapte entièrement à votre itinéraire (max 3 min). Idéal en ville. Premium, une fois par jour.","es" to "Auto: la duración se ajusta totalmente a tu ruta (máx. 3 min). Ideal para ciudad. Premium, una vez al día.","it" to "Auto: la durata si adatta totalmente al percorso (max 3 min). Perfetto in città. Premium, una volta al giorno.","pt" to "Auto: a duração se ajusta totalmente à sua rota (máx. 3 min). Ótimo para a cidade. Premium, uma vez por dia.","ru" to "Авто: длительность полностью зависит от маршрута (до 3 мин). Отлично для города. Premium, раз в день.","ja" to "オート：長さはルートに完全に合わせて調整（最大3分）。街乗りに最適。Premium、1日1回。","zh" to "自动：时长完全根据路线调整（最长3分钟）。适合城市出行。会员专享，每天1次。","ko" to "자동: 길이가 경로에 완전히 맞춰집니다(최대 3분). 도심 이동에 적합. 프리미엄, 하루 1회.","ar" to "تلقائي: تتكيّف المدة بالكامل مع مسارك (بحد أقصى 3 دقائق). مثالي لرحلات المدينة. مميّز، مرة واحدة يوميًا."),
    "Detection sensitivity" to mapOf("tr" to "Algılama hassasiyeti","de" to "Erkennungsgenauigkeit","fr" to "Précision de détection","es" to "Precisión de detección","it" to "Precisione di rilevamento","pt" to "Precisão de detecção","ru" to "Точность отслеживания","ja" to "検出感度","zh" to "检测精度","ko" to "감지 정밀도","ar" to "دقة التتبّع"),
    "High" to mapOf("tr" to "Hassas","de" to "Hoch","fr" to "Élevée","es" to "Alta","it" to "Alta","pt" to "Alta","ru" to "Высокая","ja" to "高","zh" to "高","ko" to "높음","ar" to "عالية"),
    "Balanced" to mapOf("tr" to "Dengeli","de" to "Ausgewogen","fr" to "Équilibrée","es" to "Equilibrada","it" to "Bilanciata","pt" to "Equilibrada","ru" to "Сбаланс.","ja" to "バランス","zh" to "均衡","ko" to "균형","ar" to "متوازنة"),
    "Simple" to mapOf("tr" to "Basit","de" to "Einfach","fr" to "Simple","es" to "Simple","it" to "Semplice","pt" to "Simples","ru" to "Простая","ja" to "シンプル","zh" to "简单","ko" to "간단","ar" to "بسيطة"),
    "Location every 5s — highest detection, densest/smoothest route (a bit more battery)." to mapOf("tr" to "5 sn'de bir konum — en hassas algılama, en yoğun ve akıcı rota videosu (pil biraz daha çok).","de" to "Standort alle 5 Sek. – beste Erkennung, dichteste/flüssigste Route (etwas mehr Akku).","fr" to "Position toutes les 5 s – détection maximale, itinéraire le plus fluide (un peu plus de batterie).","es" to "Ubicación cada 5 s: máxima detección, ruta más fluida (algo más de batería).","it" to "Posizione ogni 5 s – rilevamento massimo, percorso più fluido (un po' più batteria).","pt" to "Localização a cada 5 s — detecção máxima, rota mais fluida (um pouco mais de bateria).","ru" to "Геопозиция каждые 5 с — макс. точность, самый плавный маршрут (чуть больше расхода батареи).","ja" to "5秒ごとに位置取得 — 最高の検出、最も滑らかなルート（電池をやや多く消費）。","zh" to "每5秒定位 — 检测最精准、路线最流畅（耗电略多）。","ko" to "5초마다 위치 — 최고 감지, 가장 부드러운 경로(배터리 약간 더 사용).","ar" to "تحديد الموقع كل 5 ث — أعلى دقة وأكثر مسار سلاسة (استهلاك بطارية أكبر قليلًا)."),
    "~Every 15s — balanced: good detection, reasonable battery." to mapOf("tr" to "~15 sn'de bir — dengeli: iyi algılama, makul pil.","de" to "~Alle 15 Sek. – ausgewogen: gute Erkennung, vertretbarer Akku.","fr" to "~Toutes les 15 s – équilibré : bonne détection, batterie raisonnable.","es" to "~Cada 15 s: equilibrado, buena detección y batería razonable.","it" to "~Ogni 15 s – bilanciato: buon rilevamento, batteria ragionevole.","pt" to "~A cada 15 s — equilibrado: boa detecção, bateria razoável.","ru" to "~Каждые 15 с — баланс: хорошая точность, умеренный расход.","ja" to "~15秒ごと — バランス：良好な検出、適度な電池消費。","zh" to "~每15秒 — 均衡：检测良好，耗电适中。","ko" to "~15초마다 — 균형: 좋은 감지, 적당한 배터리.","ar" to "~كل 15 ث — متوازن: كشف جيد واستهلاك معقول للبطارية."),
    "~Every 45s — most efficient/battery-friendly, coarser detection." to mapOf("tr" to "~45 sn'de bir — en performanslı ve pil dostu, daha kaba algılama.","de" to "~Alle 45 Sek. – am effizientesten/akkuschonend, gröbere Erkennung.","fr" to "~Toutes les 45 s – le plus économe en batterie, détection plus grossière.","es" to "~Cada 45 s: lo más eficiente para la batería, detección más básica.","it" to "~Ogni 45 s – il più efficiente per la batteria, rilevamento più grossolano.","pt" to "~A cada 45 s — mais eficiente/poupa bateria, detecção mais básica.","ru" to "~Каждые 45 с — экономнее всего для батареи, грубее точность.","ja" to "~45秒ごと — 最も省電力、検出は粗め。","zh" to "~每45秒 — 最省电，检测较粗略。","ko" to "~45초마다 — 가장 효율적/배터리 절약, 감지는 거침.","ar" to "~كل 45 ث — الأوفر للبطارية، كشف أقل دقة."),
    "High & Balanced need Premium — finer detection + smoother video." to mapOf("tr" to "Hassas ve Dengeli için Premium gerekir — daha hassas algılama + daha akıcı video.","de" to "Hoch & Ausgewogen erfordern Premium – feinere Erkennung + flüssigeres Video.","fr" to "Élevée et Équilibrée nécessitent Premium – détection plus fine + vidéo plus fluide.","es" to "Alta y Equilibrada requieren Premium: detección más fina y vídeo más fluido.","it" to "Alta ed Equilibrata richiedono Premium – rilevamento più preciso + video più fluido.","pt" to "Alta e Equilibrada exigem Premium — detecção mais precisa + vídeo mais fluido.","ru" to "Высокая и Сбалансированная требуют Premium — точнее отслеживание и плавнее видео.","ja" to "「高」と「バランス」はPremiumが必要 — より精密な検出と滑らかな動画。","zh" to "「高」和「均衡」需会员 — 更精准检测 + 更流畅视频。","ko" to "높음·균형은 프리미엄 필요 — 더 정밀한 감지 + 더 부드러운 영상.","ar" to "تتطلب «عالية» و«متوازنة» الاشتراك المميّز — كشف أدق وفيديو أكثر سلاسة."),
    "Rendering in cloud" to mapOf("tr" to "Bulutta hazırlanıyor 🎬","de" to "Wird in der Cloud erstellt 🎬","fr" to "Création dans le cloud 🎬","es" to "Generando en la nube 🎬","it" to "Creazione nel cloud 🎬","pt" to "Gerando na nuvem 🎬","ru" to "Создаётся в облаке 🎬","ja" to "クラウドで作成中 🎬","zh" to "正在云端生成 🎬","ko" to "클라우드에서 생성 중 🎬","ar" to "جارٍ الإنشاء في السحابة 🎬"),
    "Automatic video" to mapOf("tr" to "Otomatik video","de" to "Automatisches Video","fr" to "Vidéo automatique","es" to "Vídeo automático","it" to "Video automatico","pt" to "Vídeo automático","ru" to "Автоматическое видео","ja" to "自動ビデオ","zh" to "自动视频","ko" to "자동 동영상","ar" to "فيديو تلقائي"),
    "Auto-made after each trip" to mapOf("tr" to "Gezi bitince otomatik üretilir","de" to "Wird nach jeder Fahrt automatisch erstellt","fr" to "Créée automatiquement après chaque sortie","es" to "Se crea automáticamente tras cada viaje","it" to "Creato automaticamente dopo ogni giro","pt" to "Criado automaticamente após cada viagem","ru" to "Создаётся автоматически после каждой поездки","ja" to "移動のたびに自動作成","zh" to "每次出行后自动生成","ko" to "이동할 때마다 자동 생성","ar" to "يُنشأ تلقائيًا بعد كل رحلة"),
    "High resolution, no logo" to mapOf("tr" to "Yüksek çözünürlük, logo yok","de" to "Hohe Auflösung, kein Logo","fr" to "Haute résolution, sans logo","es" to "Alta resolución, sin logo","it" to "Alta risoluzione, senza logo","pt" to "Alta resolução, sem logo","ru" to "Высокое разрешение, без логотипа","ja" to "高解像度・ロゴなし","zh" to "高分辨率，无标志","ko" to "고해상도, 로고 없음","ar" to "دقة عالية، بدون شعار"),
    "Camera distance" to mapOf("tr" to "Kamera mesafesi","de" to "Kameradistanz","fr" to "Distance caméra","es" to "Distancia de cámara","it" to "Distanza camera","pt" to "Distância da câmera","ru" to "Дистанция камеры","ja" to "カメラ距離","zh" to "镜头距离","ko" to "카메라 거리","ar" to "مسافة الكاميرا"),
    "Near" to mapOf("tr" to "Yakın","de" to "Nah","fr" to "Proche","es" to "Cerca","it" to "Vicino","pt" to "Perto","ru" to "Близко","ja" to "近い","zh" to "近","ko" to "가까이","ar" to "قريب"),
    "Medium" to mapOf("tr" to "Orta","de" to "Mittel","fr" to "Moyen","es" to "Medio","it" to "Medio","pt" to "Médio","ru" to "Средне","ja" to "中","zh" to "中","ko" to "중간","ar" to "متوسط"),
    "Far" to mapOf("tr" to "Uzak","de" to "Fern","fr" to "Loin","es" to "Lejos","it" to "Lontano","pt" to "Longe","ru" to "Далеко","ja" to "遠い","zh" to "远","ko" to "멀리","ar" to "بعيد"),
    "How close the camera follows: Near = tighter shot, Far = wider framing." to mapOf("tr" to "Kameranın rotaya yakınlığı: Yakın daha yakın çekim, Uzak daha geniş kadraj.","de" to "Wie nah die Kamera folgt: Nah = engerer Ausschnitt, Fern = weiteres Bild.","fr" to "Distance de suivi de la caméra : Proche = plan serré, Loin = cadrage large.","es" to "Qué tan cerca sigue la cámara: Cerca = plano cerrado, Lejos = encuadre amplio.","it" to "Quanto vicino segue la camera: Vicino = inquadratura stretta, Lontano = campo ampio.","pt" to "Quão perto a câmera segue: Perto = plano fechado, Longe = enquadramento amplo.","ru" to "Насколько близко следует камера: Близко = крупнее план, Далеко = шире кадр.","ja" to "カメラの追従距離：近い=寄りの画、遠い=広い画。","zh" to "镜头跟随距离：近=更紧凑画面，远=更宽广取景。","ko" to "카메라 추적 거리: 가까이=타이트한 화면, 멀리=넓은 화면.","ar" to "مدى قرب الكاميرا: قريب = لقطة أضيق، بعيد = إطار أوسع."),
    "Camera distance is a Premium option." to mapOf("tr" to "Kamera mesafesi Premium ile seçilebilir.","de" to "Kameradistanz ist eine Premium-Option.","fr" to "La distance caméra est une option Premium.","es" to "La distancia de cámara es una opción Premium.","it" to "La distanza camera è un'opzione Premium.","pt" to "A distância da câmera é uma opção Premium.","ru" to "Дистанция камеры — опция Premium.","ja" to "カメラ距離はPremiumオプションです。","zh" to "镜头距离为会员选项。","ko" to "카메라 거리는 프리미엄 옵션입니다.","ar" to "مسافة الكاميرا خيار مميّز."),
    "Car" to mapOf("tr" to "Araba","de" to "Auto","fr" to "Voiture","es" to "Coche","it" to "Auto","pt" to "Carro","ru" to "Машина","ja" to "車","zh" to "汽车","ko" to "자동차","ar" to "سيارة"),
    "Create video" to mapOf("tr" to "Video oluştur","de" to "Video erstellen","fr" to "Créer une vidéo","es" to "Crear vídeo","it" to "Crea video","pt" to "Criar vídeo","ru" to "Создать видео","ja" to "ビデオを作成","zh" to "生成视频","ko" to "동영상 만들기","ar" to "إنشاء فيديو"),
    "Couldn't read the file" to mapOf("tr" to "Dosya okunamadı","de" to "Datei konnte nicht gelesen werden","fr" to "Impossible de lire le fichier","es" to "No se pudo leer el archivo","it" to "Impossibile leggere il file","pt" to "Não foi possível ler o arquivo","ru" to "Не удалось прочитать файл","ja" to "ファイルを読み込めませんでした","zh" to "无法读取文件","ko" to "파일을 읽을 수 없습니다","ar" to "تعذّر قراءة الملف"),
    "Upload failed — pick a valid GPX/TCX file" to mapOf("tr" to "Yükleme başarısız — geçerli bir GPX/TCX dosyası seç","de" to "Upload fehlgeschlagen – wähle eine gültige GPX/TCX-Datei","fr" to "Échec de l'import — choisis un fichier GPX/TCX valide","es" to "Error al subir — elige un archivo GPX/TCX válido","it" to "Caricamento fallito — scegli un file GPX/TCX valido","pt" to "Falha no envio — escolha um arquivo GPX/TCX válido","ru" to "Ошибка загрузки — выберите корректный файл GPX/TCX","ja" to "アップロード失敗 — 有効なGPX/TCXファイルを選んでください","zh" to "上传失败 — 请选择有效的 GPX/TCX 文件","ko" to "업로드 실패 — 올바른 GPX/TCX 파일을 선택하세요","ar" to "فشل الرفع — اختر ملف GPX/TCX صالح"),
)

fun L(tr: String, en: String): String {
    val lang = currentLang()
    if (lang == "tr") return tr
    if (lang == "en") return en
    return TRANS[en]?.get(lang) ?: en
}
